name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération des données
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_GITHUB }}
          submodules: true

      - name: Mise à jour des submodules ecedi
        run: |
          git submodule update --remote themes/rennes-hugo-theme
          git config --global user.name "github-bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add .
          git commit -m "🚀 Updated Rennes theme version" || echo "No changes to commit"
          git push origin main